import Head from 'next/head'

import React, { useState, useEffect  } from "react"

import ReactPaginate from "react-paginate"
import { useRouter } from "next/router"
import Loading from './Loading';
import Style from '../styles/Home.module.css';
import {config} from '../pages/api/config';
import {get} from 'lodash';
export default function Allmovies({data,loading}) {
let movieDetails=data.results
  console.log('data',data)
  const [movies, setmovies] = useState([])
  const router = useRouter()


  

  useEffect(() => {
    if (movieDetails) {
      if (movieDetails.error) {
        // Handle error
      } else {
        // Set movies from data
        setmovies(movieDetails)
      }
    }
  }, [movieDetails])

  const handlePagination = page => {
    const path = router.pathname
    const query = router.query
    query.page = page.selected + 1
    router.push({
      pathname: path,
      query: query || 1,
    })
  }



  return (
   
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>

        <div >
        {loading && movies ? <div>
          <div  className={Style.movies}>
        
        { movieDetails.map((items)=>{

          return (
        
            <div className={Style.card} key={items.id}>
              <div className={Style.grid}>
               <div className={Style.img}> 
               <img src={`${config.API_IMAGE.small}/${items.poster_path}`}  width="100px" height="100px"  alt="img" />
       
               </div>
             
              <div className={Style.movieQuality}>
              <p className={Style.new}>{items.vote_average  }</p>
              <p className={Style.hd}>{items.original_language }</p>
              </div>
              <p>{items.original_title}</p>
          <button className={Style.button} type="button" onClick={() => router.push(`/aboutmovie/${items.id}`)}>
      Click me
    </button>
              </div>
              </div>
       )
        }) }
        </div>

        <div className={Style.pagination}>   
        <ReactPaginate
        marginPagesDisplayed={2}
        pageRangeDisplayed={5}
        previousLabel={"previous"}
        nextLabel={"next"}
        breakLabel={"..."}
        initialPage={1}
        pageCount={20}
        onPageChange={handlePagination}
      /></div>
     
            </div>:<Loading/>}

    </div>
       <div>
       
       </div>
     
    </div>
 
  );
  }

